### ISSUE TITLE
Question: Do you think I can just use this?

### ISSUE THREAD

**Issue by StevenACoffman** [loicalleyne/leftshove#1]
Hey, this looks pretty fantastic! 

I have a PostgreSQL database that I'd like to copy into BigQuery. However, the DDL for PostgreSQL is nontrivially different from the BigQuery DDL, so translating my PostgreSQL schema into BigQuery would require some translation. I think this tool will just do that for me. Do you think that correct?

I am also not clear on whether there is any necessary preparation to perform in my PostgreSQL schema to be able to use this tool. For instance, does this tool assume that there I have added `not_modified_since` tracking in my PostgreSQL schema somehow, or does that state only live in SQLite?

If I use leftshove once with `-cdc -runonce`, and after it completes, I make more changes (insert some rows) in my PostgreSQL, and then run leftshove again, will BigQuery then pick up those new changes? 

If I change my PostgreSQL schema (add a column and populate it with values) and then run leftshove again, will BigQuery then pick up those new changes?

**Comment by loicalleyne** [comment]
Hi @StevenACoffman, I made this for a use case where the database had a not_modfied_since column in most of the tables. There is an option with BigQuery to automatically add new columns and autodetect the types, I'd need to check what I set it to do, it's probably pretty easy to change if it's not auto-adding the columns.

**Comment by StevenACoffman** [comment]
Thanks for your response! It looks like a great project, and having `not_modfied_since` in the source database is an elegant way to avoid requiring more complicated state tracking anywhere else. 

For my legacy project, I'm probably going to need to use something like https://github.com/lawrencejones/pgsink
